# Generated by Django 4.1.5 on 2023-03-24 08:38

import consluting.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consluting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='FreeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[consluting.validators.validate_date])),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_days', to='consluting.expert')),
            ],
            options={
                'unique_together': {('expert', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_times', to=settings.AUTH_USER_MODEL)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='consluting.freeday')),
            ],
        ),
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_times', to='consluting.freeday')),
            ],
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experinces', to='consluting.expert')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='consluting.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'expert')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consluting.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[consluting.validators.validate_date])),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='consluting.expert')),
            ],
            options={
                'unique_together': {('expert', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='consluting.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'expert')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consluting.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'expert')},
            },
        ),
        migrations.CreateModel(
            name='ExpertConsluting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consluting.consluting')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conslutings', to='consluting.expert')),
            ],
            options={
                'unique_together': {('expert', 'consulting')},
            },
        ),
    ]
