# Generated by Django 4.1.5 on 2023-03-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consluting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freetime',
            old_name='work_day',
            new_name='free_day',
        ),
        migrations.AlterField(
            model_name='worktime',
            name='work_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='consluting.workday'),
        ),
    ]
